"""
app.py
Flask backend + simple HTML frontend for the NFC Beach Bar ordering system.
Served by Gunicorn in production.

Pages (HTML):
    GET  /nfc-writer        — admin page to register NFC tags to tables
    GET  /order             — customer order page — all validation in Python

API endpoints (JSON):
    POST /api/consume       — mark session used (called from order page if needed)
    POST /api/register-tag  — register UID → table mapping
    GET  /api/health        — health check
"""

import os
import logging
from flask import Flask, request, jsonify, render_template
from flask_cors import CORS
from dotenv import load_dotenv

from token_utils import verify_sdm_cmac
from db import (
    get_tag,
    update_last_counter,
    create_session,
    get_session,
    consume_session,
    register_tag,
)

# ---------------------------------------------------------------------------
# App setup
# ---------------------------------------------------------------------------

load_dotenv()

app = Flask(__name__)
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

BASE_URL = os.environ.get("BASE_URL", "http://localhost:5000")
CORS(app, origins=[BASE_URL])


# ===========================================================================
# HTML PAGES
# ===========================================================================

@app.route("/nfc-writer")
def nfc_writer_page():
    """
    Admin page — register NFC chip UIDs to table IDs.
    Open this on Android Chrome during one-time tag setup.
    """
    return render_template("nfc_writer.html")


@app.route("/order")
def order_page():
    """
    Customer-facing order page.
    All NFC validation happens here in Python — no JS API calls needed.

    Flow:
      1. Read uid, ctr, cmac from query string
      2. Verify CMAC cryptographically
      3. Look up tag in database
      4. Check counter > last_counter (replay protection)
      5. Create single-use session
      6. Update last_counter
      7. Consume session immediately
      8. Render page with table_id and session_id
    """
    uid  = request.args.get("uid",  "").strip().upper()
    ctr  = request.args.get("ctr",  "").strip().upper()
    cmac = request.args.get("cmac", "").strip().upper()

    def render_error(title, message):
        return render_template(
            "order.html",
            error=message,
            error_title=title,
            table_id=None,
            session_id=None,
        )

    # 1 — All three parameters must be present
    if not uid or not ctr or not cmac:
        logger.warning("Order page missing params uid=%s ctr=%s cmac=%s", uid, ctr, cmac)
        return render_error(
            "Invalid link",
            "This page must be opened by tapping an NFC tag, not by typing the URL manually."
        )

    # 2 — Cryptographic CMAC verification
    if not verify_sdm_cmac(uid, ctr, cmac):
        logger.warning("CMAC failed uid=%s ctr=%s", uid, ctr)
        return render_error(
            "Tap rejected",
            "This link is invalid or was not generated by a genuine NFC tag."
        )

    # 3 — Look up the tag in the database
    tag = get_tag(uid)
    if not tag:
        logger.warning("Unregistered tag uid=%s", uid)
        return render_error(
            "Tag not registered",
            "This tag has not been set up yet. Please complete setup in /nfc-writer first."
        )

    # 4 — Replay protection
    incoming_counter = int(ctr, 16)
    last_counter     = tag.get("last_counter", 0)

    if incoming_counter <= last_counter:
        logger.warning("Replay detected uid=%s incoming=%d last=%d", uid, incoming_counter, last_counter)
        return render_error(
            "Link already used",
            "This link has already been used. Please tap the NFC tag again to get a fresh link."
        )

    # 5 — Create session
    table_id    = tag["table_id"]
    new_session = create_session(uid, table_id, incoming_counter)

    # 6 — Update last_counter — old URL is permanently dead
    update_last_counter(uid, incoming_counter)

    # 7 — Consume session immediately
    # Since validation is server-side, we consume right away
    consume_session(new_session["id"])

    logger.info("Valid tap: uid=%s table=%s session=%s", uid, table_id, new_session["id"])

    # 8 — Render the order page with table info
    return render_template(
        "order.html",
        error=None,
        error_title=None,
        table_id=table_id,
        session_id=new_session["id"],
    )


# ===========================================================================
# API ENDPOINTS
# ===========================================================================

@app.route("/api/register-tag", methods=["POST"])
def register_tag_route():
    """
    Register a NFC tag UID to a table ID.
    Called by the /nfc-writer page during one-time tag setup.

    Body:    { "uid": "04A1B2C3D4E5F6", "tableId": "Table-7" }
    Returns: { "success": true, "uid": "...", "tableId": "..." }
    """
    body     = request.get_json(silent=True) or {}
    uid      = body.get("uid",     "").strip().upper()
    table_id = body.get("tableId", "").strip()

    if not uid:
        return jsonify({"error": "Missing uid"}), 400
    if not table_id:
        return jsonify({"error": "Missing tableId"}), 400

    tag = register_tag(uid, table_id)

    logger.info("Tag registered: uid=%s table=%s", uid, table_id)

    return jsonify({
        "success": True,
        "uid":     tag["uid"],
        "tableId": tag["table_id"],
    }), 200


@app.route("/api/health", methods=["GET"])
def health():
    """Health check — confirms server is running."""
    return jsonify({"status": "ok"}), 200


# ===========================================================================
# Error handlers
# ===========================================================================

@app.errorhandler(404)
def not_found(e):
    return jsonify({"error": "Route not found"}), 404

@app.errorhandler(405)
def method_not_allowed(e):
    return jsonify({"error": "Method not allowed"}), 405

@app.errorhandler(500)
def server_error(e):
    logger.error("Internal server error: %s", str(e))
    return jsonify({"error": "Internal server error"}), 500


# ===========================================================================
# Entry point — local development only
# Gunicorn bypasses this block in production
# ===========================================================================

if __name__ == "__main__":
    port  = int(os.environ.get("PORT", 5000))
    debug = os.environ.get("FLASK_ENV") == "development"
    logger.info("Starting Flask NFC backend on port %d (debug=%s)", port, debug)
    app.run(host="0.0.0.0", port=port, debug=debug)